### ISSUE TITLE
directory error when running compile_ffmpeg_Ubuntu.sh

### ISSUE THREAD

**Issue by JudsonHat** [steventrux/castize#7]
Hello! This script is so useful, thanks!

I could not get compile_ffmpeg_Ubuntu.sh to run properly until i changed line 50 from 
'cd ffmpeg' to 'cd ffmpeg-$ffmpeg' 

The folder created after tar i's not 'ffmpeg' but 'ffmpeg-2.7.2'

**Comment by steventrux** [comment]
Thank you, will check it
